services:
  image-search-service:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes: 
      - "./pretrained_model:/pretrained_model"
      - precomputed_image_embeddings:/precomputed
    environment:
      DB_HOST: "db"
    depends_on:
      precompute-image-embeddings:
        condition: service_completed_successfully
      db:
        condition: service_healthy

  precompute-image-embeddings:
    build:
      context: ./
      dockerfile: precompute.Dockerfile
    volumes:
      - "./images:/images"
      - "./pretrained_model:/pretrained_model"
      - precomputed_image_embeddings:/precomputed
  db:
    image: postgres:16.10-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "db"
    volumes:
      - db-data:/var/lib/postgresql/data
      - "./healthchecks:/healthchecks"
    ports:
      - 5432:5432
    healthcheck:
      test: /healthchecks/postgres.sh
      interval: "5s"

volumes:
  precomputed_image_embeddings:
  db-data:
    
